server:
  port: 80 #http请求默认就是80端口，所以请求时地址栏可以省略不写端口号
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: false # 表示是否将自己注册进EurekaServer，默认为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版

ribbon:
  ReadTimeout: 5000 # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000 # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug
